name: PR Preview

on:
  pull_request:
    branches:
      - main

jobs:
  fingerprint:
    name: Fingerprint
    type: fingerprint

  get_ios_build:
    name: Check existing iOS build
    needs: [fingerprint]
    type: get-build
    params:
      fingerprint_hash: ${{ needs.fingerprint.outputs.ios_fingerprint_hash }}
      profile: development-simulator

  get_android_build:
    name: Check existing Android build
    needs: [fingerprint]
    type: get-build
    params:
      fingerprint_hash: ${{ needs.fingerprint.outputs.android_fingerprint_hash }}
      profile: development

  build_ios:
    name: Build iOS dev client
    needs: [get_ios_build]
    if: ${{ !needs.get_ios_build.outputs.build_id }}
    type: build
    params:
      platform: ios
      profile: development-simulator

  build_android:
    name: Build Android dev client
    needs: [get_android_build]
    if: ${{ !needs.get_android_build.outputs.build_id }}
    type: build
    params:
      platform: android
      profile: development

  publish_preview:
    name: Publish preview update
    needs: [fingerprint]
    type: update
    params:
      branch: ${{ github.ref_name }}

  comment_on_pr:
    name: Comment on PR
    after: [build_ios, build_android, publish_preview]
    type: github-comment
